// Pepper - Daily Briefing Cron
import { getSlackContext } from './slack-context.js';
import { getCalendarContext } from './google-calendar.js';
import { getGmailContext } from './gmail.js';

const SYSTEM_PROMPT = `You are Pepper, the Chief of Staff to John B Lin, COO of Paceline (paceline.fit). You are a trusted senior operator.

About Paceline: Health and fitness rewards platform. Users earn Pacepoints by hitting weekly heart-rate activity goals via wearables. Tagline: "Healthy Feels Good."

Strategic context: Paceline operates alongside MiYA insurance acquisition strategy. Core priority: standalone commercial traction independent of MiYA/Antex timelines.

Top priorities:
1. Mass market app evolution - non-wearable users, Android, Antex policyholder activation
2. Validating initiatives outside Antex - Paceline+, insurance brokerage, credit card, employer health, B2B intelligence

Team (Slack-first):
- Sam Luff - product/strategy
- Dave Sharp - insurance project manager
- Stan Liang - product manager
- Colin Miiller - engineering
- Catherine Nally - brand/marketing
- James Hale - data/research
- Heather Shetrawski - customer support
- Katrina Chanco - design/product
- Anil Lodhia - design
- Amanda - human Chief of Staff. Prepares ELT and team materials. John and Nick review/edit before sending.

ELT: Joel, Tom, Terry, Tyler (email-first), Nick Wright (CMO/Chief Commercial, John's peer, on ELT)

ELT materials protocol: Substantive ELT materials need a pre-read summary OR must be sent 1 business day in advance. Always flag this lead time.

Base the briefing entirely on real Slack, Calendar, and Gmail context provided. Reference real people, conversations, meetings, and email threads. Don't fabricate anything not in the data.`;

export default async function handler(req, res) {
  const authHeader = req.headers['authorization'];
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}` && process.env.NODE_ENV !== 'development') {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  try {
    // Pull all context in parallel
    const [slackContext, calendarContext, gmailContext] = await Promise.all([
      getSlackContext(8, 20),
      getCalendarContext(3),
      getGmailContext(10),
    ]);

    const today = new Date().toLocaleDateString('en-US', {
      weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
    });

    const prompt = `Generate today's Daily Briefing for John. Today is ${today}.

LIVE SLACK CONTEXT:
${slackContext}

UPCOMING CALENDAR (next 3 days):
${calendarContext}

RECENT EMAIL (unread + ELT threads):
${gmailContext}

Based on this real data, generate the briefing. Reference specific people, threads, meetings, and email threads. For the Schedule Snapshot use actual calendar events. Flag ELT meetings needing pre-reads. Surface stale email threads that need a reply. Don't fabricate anything not in the data.

Format for Slack - keep bullets to 1-2 lines, no preamble:

*🔴 Needs John Today*
*🟡 On Deck - Next 72 hrs*
*📬 Comms to Review / Send*
*📅 Schedule Snapshot*
*💡 One Proactive Suggestion*`;

    const claudeRes = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-api-key': process.env.ANTHROPIC_API_KEY, 'anthropic-version': '2023-06-01' },
      body: JSON.stringify({ model: 'claude-sonnet-4-20250514', max_tokens: 1000, system: SYSTEM_PROMPT, messages: [{ role: 'user', content: prompt }] }),
    });

    const claudeData = await claudeRes.json();
    const briefingText = claudeData.content?.[0]?.text;
    if (!briefingText) throw new Error('No content from Claude: ' + JSON.stringify(claudeData));

    const slackRes = await fetch('https://slack.com/api/chat.postMessage', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.SLACK_BOT_TOKEN}` },
      body: JSON.stringify({
        channel: process.env.JOHN_SLACK_USER_ID,
        blocks: [
          { type: 'header', text: { type: 'plain_text', text: 'Pepper - Daily Briefing', emoji: true } },
          { type: 'context', elements: [{ type: 'mrkdwn', text: `${today}  ·  Paceline Chief of Staff` }] },
          { type: 'divider' },
          { type: 'section', text: { type: 'mrkdwn', text: briefingText } },
          { type: 'divider' },
          { type: 'context', elements: [{ type: 'mrkdwn', text: '_Generated by Pepper · Reply with any task_' }] },
        ],
        text: `Pepper · Daily Briefing · ${today}`,
        unfurl_links: false,
      }),
    });

    const slackData = await slackRes.json();
    if (!slackData.ok) throw new Error('Slack error: ' + slackData.error);

    return res.status(200).json({ ok: true, ts: slackData.ts });
  } catch (err) {
    console.error('Pepper briefing error:', err);
    return res.status(500).json({ error: err.message });
  }
}
